#!/bin/bash
# Script that creates titles in ASS format from an input JSON file.

# FUNCTION: Calculates the timecode value in HH:MM:SS format when a time in seconds is supplied.
Calculate_Timecode () {
        num=$1
        min=0
        hour=0
        day=0
        if((num>59));
        then
                ((sec=num%60))
                ((num=num/60))
                if((num>59));
                then
                        ((min=num%60))
                        ((hour=num/60))
                else
                        ((min=num))
                fi
        else
                ((sec=num))
        fi

        echo $( printf "%02d" $hour ):$( printf "%02d" $min ):$( printf "%02d" $sec )
}

# Calculate timecodes for SRT file.
TC_DURATION_SECONDS=$( ffprobe -i $( jq -r '.edit_info.audio_file' $INPUT_DIRECTORY/$INPUT_METADATA ) -show_format -v quiet | sed -n 's/duration=//p' | cut -d. -f1 )
TC_AUDIO_INTRO_TITLE_START="00:00:03"
TC_AUDIO_INTRO_TITLE_END="00:00:10"
TC_VIDEO_INTRO_TITLE_START="00:00:13"
TC_VIDEO_INTRO_TITLE_END="00:00:20"
TC_AUDIO_OUTRO_TITLE_START=$( Calculate_Timecode $(( $TC_DURATION_SECONDS - 20 )) )
TC_AUDIO_OUTRO_TITLE_END=$( Calculate_Timecode $(( $TC_DURATION_SECONDS - 13 )) )
TC_VIDEO_OUTRO_TITLE_START=$( Calculate_Timecode $(( $TC_DURATION_SECONDS - 10 )) )
TC_VIDEO_OUTRO_TITLE_END=$( Calculate_Timecode $(( $TC_DURATION_SECONDS - 3 )) )

#CREDIT_AUDIO="$( $( jq -r '.file.audio_stream.author' $INPUT_DIRECTORY/$INPUT_METADATA ) / "$( jq -r '.file.audio_stream.title' $INPUT_DIRECTORY/$INPUT_METADATA )" / $( jq -r '.file.audio_stream.licence' $INPUT_DIRECTORY/$INPUT_METADATA ) )"
#CREDIT_VIDEO="$( $( jq -r '.file.video_stream.author' $INPUT_DIRECTORY/$INPUT_METADATA ) / "$( jq -r '.file.video_stream.title' $INPUT_DIRECTORY/$INPUT_METADATA )" / $( jq -r '.file.video_stream.licence' $INPUT_DIRECTORY/$INPUT_METADATA ) )"

# Build the titles file in the format of an SRT file.
cat <<EOF > $INPUT_DIRECTORY/../output/$( jq -r '.file.title' $INPUT_DIRECTORY/$INPUT_METADATA ).ass
[Script Info]
; Script generated by Kardashev Ingester
; https://github.com/brotherkaif/kardashev-ingester 
Title: $( jq -r '.file.title' $INPUT_DIRECTORY/$INPUT_METADATA )
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
YCbCr Matrix: None

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Arial,10,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,3,2,0,1,10,10,10,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,$TC_AUDIO_INTRO_TITLE_START.00,$TC_AUDIO_INTRO_TITLE_END.00,Default,,0,0,0,,[AUDIO]\N"$( jq -r '.file.audio_stream.title' $INPUT_DIRECTORY/$INPUT_METADATA )" / $( jq -r '.file.audio_stream.author' $INPUT_DIRECTORY/$INPUT_METADATA ) / $( jq -r '.file.audio_stream.licence' $INPUT_DIRECTORY/$INPUT_METADATA )
Dialogue: 0,$TC_VIDEO_INTRO_TITLE_START.00,$TC_VIDEO_INTRO_TITLE_END.00,Default,,0,0,0,,[VIDEO]\N"$( jq -r '.file.video_stream.title' $INPUT_DIRECTORY/$INPUT_METADATA )" / $( jq -r '.file.video_stream.author' $INPUT_DIRECTORY/$INPUT_METADATA ) / $( jq -r '.file.video_stream.licence' $INPUT_DIRECTORY/$INPUT_METADATA )
Dialogue: 0,$TC_AUDIO_OUTRO_TITLE_START.00,$TC_AUDIO_OUTRO_TITLE_END.00,Default,,0,0,0,,[AUDIO]\N"$( jq -r '.file.audio_stream.title' $INPUT_DIRECTORY/$INPUT_METADATA )" / $( jq -r '.file.audio_stream.author' $INPUT_DIRECTORY/$INPUT_METADATA ) / $( jq -r '.file.audio_stream.licence' $INPUT_DIRECTORY/$INPUT_METADATA )
Dialogue: 0,$TC_VIDEO_OUTRO_TITLE_START.00,$TC_VIDEO_OUTRO_TITLE_END.00,Default,,0,0,0,,[VIDEO]\N"$( jq -r '.file.video_stream.title' $INPUT_DIRECTORY/$INPUT_METADATA )" / $( jq -r '.file.video_stream.author' $INPUT_DIRECTORY/$INPUT_METADATA ) / $( jq -r '.file.video_stream.licence' $INPUT_DIRECTORY/$INPUT_METADATA )
EOF
